/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace SplitWiseGroup {
  export type ExpenseStruct = {
    payer: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    debtor_addresses: PromiseOrValue<string>[];
  };

  export type ExpenseStructOutput = [string, string, BigNumber, string[]] & {
    payer: string;
    name: string;
    amount: BigNumber;
    debtor_addresses: string[];
  };
}

export interface SplitWiseGroupInterface extends utils.Interface {
  functions: {
    "activeMembers(uint256)": FunctionFragment;
    "addExpense(address,string,address[],uint256)": FunctionFragment;
    "addToWhitelist(address[])": FunctionFragment;
    "close()": FunctionFragment;
    "debts(address,address)": FunctionFragment;
    "expenses(uint256)": FunctionFragment;
    "expensesLength()": FunctionFragment;
    "getActiveMember(uint256)": FunctionFragment;
    "getActiveMembers()": FunctionFragment;
    "getActiveMembersCount()": FunctionFragment;
    "getDebt(address,address)": FunctionFragment;
    "getExpense(uint256)": FunctionFragment;
    "isClosed()": FunctionFragment;
    "isMember(address)": FunctionFragment;
    "isSettled()": FunctionFragment;
    "isWhitelisted(address)": FunctionFragment;
    "join()": FunctionFragment;
    "members(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "removeFromWhitelist(address[])": FunctionFragment;
    "removeMember(address)": FunctionFragment;
    "requiredAmount()": FunctionFragment;
    "send(uint256,address)": FunctionFragment;
    "settleDebt()": FunctionFragment;
    "settleGroup()": FunctionFragment;
    "stakes(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "activeMembers"
      | "addExpense"
      | "addToWhitelist"
      | "close"
      | "debts"
      | "expenses"
      | "expensesLength"
      | "getActiveMember"
      | "getActiveMembers"
      | "getActiveMembersCount"
      | "getDebt"
      | "getExpense"
      | "isClosed"
      | "isMember"
      | "isSettled"
      | "isWhitelisted"
      | "join"
      | "members"
      | "owner"
      | "removeFromWhitelist"
      | "removeMember"
      | "requiredAmount"
      | "send"
      | "settleDebt"
      | "settleGroup"
      | "stakes",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activeMembers",
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "addExpense",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "addToWhitelist",
    values: [PromiseOrValue<string>[]],
  ): string;
  encodeFunctionData(functionFragment: "close", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "debts",
    values: [PromiseOrValue<string>, PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "expenses",
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "expensesLength",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveMember",
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveMembers",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveMembersCount",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "getDebt",
    values: [PromiseOrValue<string>, PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "getExpense",
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: "isClosed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(functionFragment: "isSettled", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(functionFragment: "join", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeFromWhitelist",
    values: [PromiseOrValue<string>[]],
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "requiredAmount",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "settleDebt",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "settleGroup",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [PromiseOrValue<string>],
  ): string;

  decodeFunctionResult(
    functionFragment: "activeMembers",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "addExpense", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addToWhitelist",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "close", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "debts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expenses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expensesLength",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveMember",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveMembers",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveMembersCount",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "getDebt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getExpense", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isClosed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSettled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "join", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeFromWhitelist",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredAmount",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settleDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleGroup",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;

  events: {
    "ExpenseAdded(uint256,address,uint256,string,address[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExpenseAdded"): EventFragment;
}

export interface ExpenseAddedEventObject {
  expenseIndex: BigNumber;
  payer: string;
  amount: BigNumber;
  name: string;
  debtor_addresses: string[];
}
export type ExpenseAddedEvent = TypedEvent<
  [BigNumber, string, BigNumber, string, string[]],
  ExpenseAddedEventObject
>;

export type ExpenseAddedEventFilter = TypedEventFilter<ExpenseAddedEvent>;

export interface SplitWiseGroup extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SplitWiseGroupInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    activeMembers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    addExpense(
      _payer: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _debtor_addresses: PromiseOrValue<string>[],
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    addToWhitelist(
      newMembers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    close(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    debts(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    expenses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, BigNumber] & {
        payer: string;
        name: string;
        amount: BigNumber;
      }
    >;

    expensesLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getActiveMember(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    getActiveMembers(overrides?: CallOverrides): Promise<[string[]]>;

    getActiveMembersCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDebt(
      debtor: PromiseOrValue<string>,
      creditor: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    getExpense(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[SplitWiseGroup.ExpenseStructOutput]>;

    isClosed(overrides?: CallOverrides): Promise<[boolean]>;

    isMember(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    isSettled(overrides?: CallOverrides): Promise<[boolean]>;

    isWhitelisted(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    join(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    removeFromWhitelist(
      membersToRemove: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    removeMember(
      memberToRemove: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    requiredAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    send(
      amount: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    settleDebt(overrides?: CallOverrides): Promise<[void]>;

    settleGroup(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    stakes(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;
  };

  activeMembers(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<string>;

  addExpense(
    _payer: PromiseOrValue<string>,
    _name: PromiseOrValue<string>,
    _debtor_addresses: PromiseOrValue<string>[],
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  addToWhitelist(
    newMembers: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  close(
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  debts(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  expenses(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<
    [string, string, BigNumber] & {
      payer: string;
      name: string;
      amount: BigNumber;
    }
  >;

  expensesLength(overrides?: CallOverrides): Promise<BigNumber>;

  getActiveMember(
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<string>;

  getActiveMembers(overrides?: CallOverrides): Promise<string[]>;

  getActiveMembersCount(overrides?: CallOverrides): Promise<BigNumber>;

  getDebt(
    debtor: PromiseOrValue<string>,
    creditor: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  getExpense(
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<SplitWiseGroup.ExpenseStructOutput>;

  isClosed(overrides?: CallOverrides): Promise<boolean>;

  isMember(
    member: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  isSettled(overrides?: CallOverrides): Promise<boolean>;

  isWhitelisted(
    member: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  join(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  members(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  removeFromWhitelist(
    membersToRemove: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  removeMember(
    memberToRemove: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  requiredAmount(overrides?: CallOverrides): Promise<BigNumber>;

  send(
    amount: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  settleDebt(overrides?: CallOverrides): Promise<void>;

  settleGroup(
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  stakes(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  callStatic: {
    activeMembers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<string>;

    addExpense(
      _payer: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _debtor_addresses: PromiseOrValue<string>[],
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    addToWhitelist(
      newMembers: PromiseOrValue<string>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    close(overrides?: CallOverrides): Promise<void>;

    debts(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    expenses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, BigNumber] & {
        payer: string;
        name: string;
        amount: BigNumber;
      }
    >;

    expensesLength(overrides?: CallOverrides): Promise<BigNumber>;

    getActiveMember(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<string>;

    getActiveMembers(overrides?: CallOverrides): Promise<string[]>;

    getActiveMembersCount(overrides?: CallOverrides): Promise<BigNumber>;

    getDebt(
      debtor: PromiseOrValue<string>,
      creditor: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getExpense(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<SplitWiseGroup.ExpenseStructOutput>;

    isClosed(overrides?: CallOverrides): Promise<boolean>;

    isMember(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    isSettled(overrides?: CallOverrides): Promise<boolean>;

    isWhitelisted(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    join(overrides?: CallOverrides): Promise<void>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    removeFromWhitelist(
      membersToRemove: PromiseOrValue<string>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    removeMember(
      memberToRemove: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    requiredAmount(overrides?: CallOverrides): Promise<BigNumber>;

    send(
      amount: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    settleDebt(overrides?: CallOverrides): Promise<void>;

    settleGroup(overrides?: CallOverrides): Promise<void>;

    stakes(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  filters: {
    "ExpenseAdded(uint256,address,uint256,string,address[])"(
      expenseIndex?: null,
      payer?: null,
      amount?: null,
      name?: null,
      debtor_addresses?: null,
    ): ExpenseAddedEventFilter;
    ExpenseAdded(
      expenseIndex?: null,
      payer?: null,
      amount?: null,
      name?: null,
      debtor_addresses?: null,
    ): ExpenseAddedEventFilter;
  };

  estimateGas: {
    activeMembers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    addExpense(
      _payer: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _debtor_addresses: PromiseOrValue<string>[],
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    addToWhitelist(
      newMembers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    close(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    debts(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    expenses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    expensesLength(overrides?: CallOverrides): Promise<BigNumber>;

    getActiveMember(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getActiveMembers(overrides?: CallOverrides): Promise<BigNumber>;

    getActiveMembersCount(overrides?: CallOverrides): Promise<BigNumber>;

    getDebt(
      debtor: PromiseOrValue<string>,
      creditor: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getExpense(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isClosed(overrides?: CallOverrides): Promise<BigNumber>;

    isMember(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isSettled(overrides?: CallOverrides): Promise<BigNumber>;

    isWhitelisted(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    join(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    removeFromWhitelist(
      membersToRemove: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    removeMember(
      memberToRemove: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    requiredAmount(overrides?: CallOverrides): Promise<BigNumber>;

    send(
      amount: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    settleDebt(overrides?: CallOverrides): Promise<BigNumber>;

    settleGroup(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    stakes(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    activeMembers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    addExpense(
      _payer: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _debtor_addresses: PromiseOrValue<string>[],
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    addToWhitelist(
      newMembers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    close(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    debts(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    expenses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    expensesLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getActiveMember(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getActiveMembers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getActiveMembersCount(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getDebt(
      debtor: PromiseOrValue<string>,
      creditor: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getExpense(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isClosed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isMember(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isSettled(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isWhitelisted(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    join(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeFromWhitelist(
      membersToRemove: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    removeMember(
      memberToRemove: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    requiredAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    send(
      amount: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    settleDebt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    settleGroup(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    stakes(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
